### ISSUE TITLE
【bpf_load_program() failed. -- err=22】

### ISSUE THREAD

**Issue by Stitches-114** [elfadel/vtl#5]
I met this problem,with a wrong message that _bpf_load_program() failed. -- err=22_, would u tell me how to solve it.

**Comment by elfadel** [comment]
@Stitches-114 please, provides me with more details. Which VTL's component triggers the error (hooker,  UI, etc.)? 
Have you correctly configure your environment for eBPF (iproute2, LLVM/Clang, etc.) ? What is your kernel version?

**Comment by Stitches-114** [comment]
When I do the step _Test and run Hooker_ in ubuntu20.04, execute the command _sudo ./vtl_ui_ in the terminal of the bin folder, select _Deploy TF_, _Activate Hooker_, and select an available device, then the error _[LAUNCHER]: bpf_load_program() failed. -- err=22_ appeared. I think my ebpf environment is all configured and my kernel version is 5.13. By the way, what is your vtl kernel version? Thanks.

**Comment by elfadel** [comment]
> By the way, what is your vtl kernel version?

v5.3.5

**Comment by Stitches-114** [comment]
We did it again with this version of the kernel and still encountered the same problem

**Comment by elfadel** [comment]
@Stitches-114 I will provide with a fix soon.

**Comment by elfadel** [comment]
@Stitches-114 please, retry with the new instructions on 'dev' branch. Let me know if it works in order to merge and close the issue.

**Comment by Stitches-114** [comment]
Sorry to bother you again,we encountered some new problems.

We launched two laptops(laptop A running a server program ,laptop B running client program) in a LAN to communicate with each other in TCP while both two machines had activated the Hooker.

Then we used Wireshark to capture packets to see which protocol is used, at first, it was TCP for sure.

After we used the hooker daemon to change the protocol from TCP to UDP in laptop A and B ,we let laptop B resend some messages to laptop A , but the package captured by the Wireshark showed that it was still using TCP.

 

That’s where we feel confused, we think we haven’t fully understood how the system is being used, or maybe we didn’t use the hk-daemon correctly.

 

Here are all problems confused us as following:

 

(1) We don’t know what the ‘inputmode’ and ‘outputmode’ is used for. Would you show me how to choose these modes by order?

 

(2) We activated the hk-daemon by using the command

' sudo ./hk-daemon 17 server’ in sever laptop, and the command

' sudo ./hk-daemon 17 client’ in client laptop.

Is that the parama of <HOST_MODE> filled right?

 

(3) After we started using the user daemon, we just launched the TCP application to communicate, we wonder if there are any further steps that we need to complete ?

**Comment by elfadel** [comment]
Hello @Stitches-114 
> (1) We don’t know what the ‘inputmode’ and ‘outputmode’ is used for. Would you show me how to choose these modes by order?

These modes are not related to Hooker component. You need to use them if only you are using the Service API provided by VTL as well as the associated customized L4 protocols.

> 2) We activated the hk-daemon by using the command
>' sudo ./hk-daemon 17 server’ in sever laptop, and the command
>' sudo ./hk-daemon 17 client’ in client laptop.
>Is that the parama of <HOST_MODE> filled right?

Yep. You are doing well.

> (3) After we started using the user daemon, we just launched the TCP application to communicate, we wonder if there are any further steps that we need to complete ?

Nope, you don't have to do any additional manipulations.

Here is the thing: I think you are using a TCP application not registered and handled by the Hooker. In fact, Hooker handles the packets of TCP applications that port are passed to it from here [link](https://github.com/elfadel/vtl/blob/2e5f3450ceba2dbaa21ffa850e4fd533cde63b65/XTFsPool/hooker_test_progs.c#L18).

This is hard-coded for now. Feel free to extend this feature in order to allow dynamic port register.

So, [here](https://github.com/elfadel/vtl/blob/2e5f3450ceba2dbaa21ffa850e4fd533cde63b65/XTFsPool/hooker_test_progs.c#L190-L196), for every receive/hooked packet, we first check if it belongs to a registered TCP application before process it further. You can retry again, but now using TCP applications provided in `tests/legacy_client` and `tests/legacy_server`.
